spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage
    username: romarekonshin
    password: '123456'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8080
