spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    ru.netology.cloudstorage: INFO
